version: 2

defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/android:api-28
  environment:
    TERM: dumb

cache_key: &cache_key
  key: cache-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

restore_cache: &restore_cache
  restore_cache:
    <<: *cache_key

save_cache: &save_cache
  save_cache:
    <<: *cache_key
    paths:
      - ~/.gradle
      - ~/.m2

export_gservices_key: &export_gservices_key
  run:
    name: Export Google Services key environment variable
    command: echo 'export GOOGLE_SERVICES_KEY="AAAAmxkfvlM:APA91bHn9FE2dty0MNSjwsSbZilc5QYmMwrG67IX0yzY5xdELs3d8O424d-BZui7eaHCZMqoVMyWMaTw11Nlu9bChmzHKeMRUK7U8o2BZ9lRBOt13JnadtHedG9ckHeGhtoj8aVEeNje"' >> $BASH_ENV

decode_gservices_key: &decode_gservices_key
  run:
    name: Decode Google Services key
    command: echo AAAAmxkfvlM:APA91bHn9FE2dty0MNSjwsSbZilc5QYmMwrG67IX0yzY5xdELs3d8O424d-BZui7eaHCZMqoVMyWMaTw11Nlu9bChmzHKeMRUK7U8o2BZ9lRBOt13JnadtHedG9ckHeGhtoj8aVEeNje | base64 -di > app/google-services.json

jobs:
  build_debug:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Download dependencies
          command: |
            sudo chmod +x ./gradlew
            ./gradlew androidDependencies
      - *save_cache
      - *export_gservices_key
      - *decode_gservices_key
      - run:
          name: Gradle build (debug)
          command: ./gradlew -PciBuild=true :app:assembleDebug :app:assembleAndroidTest
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: /apk/
      - run:
          name: Publish APK to Firebase Distribution
          command: ./gradlew assembleDebug appDistributionUploadDebug

workflows:
  version: 2
  build_test_lint:
    jobs:
      - build_debug
