version: 2

defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/android:api-28
  environment:
    TERM: dumb
    _JAVA_OPTIONS: "-Xmx3072m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"


commands:
  setup_gradle:
    steps:
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

jobs:
  build-and-test:
    <<: *defaults
    steps:
      - checkout
      - setup_gradle

workflows:
  version: 2
  build_test_lint:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master