version: 2

defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/android:api-28
  environment:
    TERM: dumb

gcloud_config: &gcloud_config
  working_directory: ~/workspace
  docker:
    - image: google/cloud-sdk:latest
  environment:
    TERM: dumb

cache_key: &cache_key
  key: cache-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

restore_cache: &restore_cache
  restore_cache:
    <<: *cache_key

save_cache: &save_cache
  save_cache:
    <<: *cache_key
    paths:
      - ~/.gradle
      - ~/.m2

export_gservices_key: &export_gservices_key
  run:
    name: Export Google Services key environment variable
    command: echo 'export GOOGLE_SERVICES_KEY="$GOOGLE_SERVICES_KEY"' >> $BASH_ENV

decode_gservices_key: &decode_gservices_key
  run:
    name: Decode Google Services key
    command: echo $GOOGLE_SERVICES_KEY | base64 -di > app/google-services.json

export_gcloud_key: &export_gcloud_key
  run:
    name: Export Google Cloud Service key environment variable
    command: echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
decode_gcloud_key: &decode_gcloud_key
  run:
    name: Decode Google Cloud credentials
    command: echo $GCLOUD_SERVICE_KEY | base64 -di > ${HOME}/client-secret.json

jobs:
  build_debug:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Download dependencies
          command: |
            sudo chmod +x ./gradlew
            ./gradlew androidDependencies
      - *save_cache
      - *export_gservices_key
      - *decode_gservices_key
      - run:
          name: Gradle build (debug)
          command: ./gradlew -PciBuild=true :app:assembleDebug :app:assembleAndroidTest
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: /apk/
  test_unit:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Download dependencies
          command: |
            sudo chmod +x ./gradlew
            ./gradlew androidDependencies
      - *save_cache
      - *export_gservices_key
      - *decode_gservices_key
      - run:
          name: Run unit tests
          command: ./gradlew -PciBuild=true :app:testDebugUnitTest
      - store_artifacts:
          path: app/build/reports/
          destination: /reports/
      - store_test_results:
          path: app/build/test-results/
          destination: /test-results/

  test_instrumented:
    <<: *gcloud_config
    steps:
      - attach_workspace:
          at: ~/workspace
      - *export_gcloud_key
      - *decode_gcloud_key
      - run:
          name: Set Google Cloud target project
          command: gcloud config set project test-circle-ci-cc385
      - run:
          name: Authenticate with Google Cloud
          command: echo $FIREBASE_SERVICE_KEY | base64 -di > ./${firebase-adminsdk-w8nuh@test-circle-ci-cc385.iam.gserviceaccount.com}
      - run:
          name: Run instrumented test on Firebase Test Lab
          command: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=sailfish,version=26,locale=en_US,orientation=portrait --environment-variables coverage=true,coverageFile=/sdcard/tmp/code-coverage/connected/coverage.ec --directories-to-pull=/sdcard/tmp --timeout 20m
      - run:
          name: Create directory to store test results
          command: mkdir firebase
      - store_artifacts:
          path: firebase/
          destination: /firebase/

workflows:
  version: 2
  build_test_lint:
    jobs:
      - build_debug
      - test_unit:
          requires:
            - build_debug
      - test_instrumented:
          requires:
            - build_debug