version: 2

defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/android:api-28
  environment:
    TERM: dumb

commands:
  setup_gradle:
    steps:
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
  step_build:
    steps:
      - run:
          name: Run Tests
          command: ./gradlew -w clean testDevelopReleaseUnitTest
      - run:
          name: Run Build
          command: ./gradlew -w clean assembleDevelopRelease
          no_output_timeout: 30m
  step_release:
    steps:
      - run:
          name: Release Note & Run Upload (Firebase AppDistribution)
            command:|
            echo $(git log --format=%B -n 1 $CIRCLE_SHA1) > ./app/release_notes.txt
            ./gradlew appDistributionUploadDevelopRelease

jobs:
  build-and-test:
    <<: *defaults
    steps:
      - checkout
      - setup_gradle
      - step_build
      - step_release
  build_debug:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: |
            sudo chmod +x ./gradlew
            ./gradlew androidDependencies
      - run:
          name: Gradle build (debug)
          command: ./gradlew -PciBuild=true :app:assembleDebug :app:assembleAndroidTest
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: /apk/
workflows:
  version: 2
  build_test_lint:
    jobs:
      - build_debug